# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'bootsnap', require: false
gem 'dotenv-rails'
gem 'dry-validation'
gem 'decent_exposure'
gem 'fast_jsonapi'
gem 'pg'
gem 'puma'
gem 'rails'
gem 'rorvswild'
gem 'kaminari'
gem 'rack-cors'
gem 'graphql'

group :development, :test do
  gem 'brakeman'
  gem 'factory_bot_rails'
  gem 'fasterer'
  gem 'ffaker'
  gem 'pry-rails'
  gem 'rails_best_practices'
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
end

group :development do
  gem 'graphiql-rails'
  gem 'better_errors' 
  gem 'binding_of_caller'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'database_cleaner'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
